tbl <- read.table("household_power_consumption.txt",sep=";",header=TRUE,string=F)
x <-paste(tbl$Date,tbl$Time)
DateTime <- strptime(x,"%d/%m/%Y %H:%M:%S")
tbl <-cbind(tbl,DateTime)
is.na(tbl) <- tbl=="?"
start <- as.POSIXct("2007-02-01 00:00:00")
fin <- as.POSIXct("2007-02-02 23:59:59")
newtbl <-subset(tbl,tbl$DateTime>=start & tbl$DateTime<=fin)
newtbl$Global_active_power <- as.numeric(newtbl$Global_active_power)
newtbl$Sub_metering_1 <- as.numeric(newtbl$Sub_metering_1)
newtbl$Sub_metering_2 <- as.numeric(newtbl$Sub_metering_2)
newtbl$Sub_metering_3 <- as.numeric(newtbl$Sub_metering_3)
newtbl$Global_reactive_power <- as.numeric(newtbl$Global_reactive_power)
newtbl$Voltage <- as.numeric(newtbl$Voltage)

png("plot4.png",480,480,"px")
par(mfrow=c(2,2))
with(newtbl, {
  plot(DateTime, Global_active_power, type="l", xlab="",ylab="Global Active Power")
  plot(DateTime, Voltage, type="l", ylab="Voltage")
  plot(DateTime,Sub_metering_1,type="n",xlab="",ylab="Energy Sub Metering")
  points(DateTime,Sub_metering_1,type="l",col="black")
  points(DateTime,Sub_metering_2,type="l",col="red")
  points(DateTime,Sub_metering_3,type="l",col="blue")
  legend("topright", pch="-", col = c("black","red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
  plot(DateTime, Global_reactive_power, type="l")
})
dev.off()
